"""Add table Car

Revision ID: 3e3b65ef6e39
Revises: 
Create Date: 2021-02-07 16:04:58.583141

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e3b65ef6e39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name_car', sa.String(length=100), nullable=True),
    sa.Column('description', sa.String(length=100), nullable=True),
    sa.Column('rental_price', sa.Float(), nullable=True),
    sa.Column('transmission', sa.Boolean(), nullable=True),
    sa.Column('picture1', sa.LargeBinary(), nullable=True),
    sa.Column('picture2', sa.LargeBinary(), nullable=True),
    sa.Column('picture3', sa.LargeBinary(), nullable=True),
    sa.Column('picture4', sa.LargeBinary(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
