"""Add column rental_status in table Car.

Revision ID: 5ff715192b1a
Revises: 3e3b65ef6e39
Create Date: 2021-02-07 16:37:33.435880

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ff715192b1a'
down_revision = '3e3b65ef6e39'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('rental_status', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'rental_status')
    # ### end Alembic commands ###
