"""Add column car_start_rental_time and car_end_rental_time in the table Car

Revision ID: 75505087388e
Revises: b177b68f3b83
Create Date: 2021-02-10 18:33:34.941156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75505087388e'
down_revision = 'b177b68f3b83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('car_end_rental_time', sa.DateTime(), nullable=True))
    op.add_column('car', sa.Column('car_start_rental_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('car', 'car_start_rental_time')
    op.drop_column('car', 'car_end_rental_time')
    # ### end Alembic commands ###
